# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 369)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_connect = QtWidgets.QPushButton(self.centralwidget)
        self.btn_connect.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_connect.setMaximumSize(QtCore.QSize(99999, 99999))
        self.btn_connect.setObjectName("btn_connect")
        self.verticalLayout_3.addWidget(self.btn_connect)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_me17 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_me17.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_me17.setMaximumSize(QtCore.QSize(99999, 99999))
        self.btn_me17.setObjectName("btn_me17")
        self.verticalLayout.addWidget(self.btn_me17)
        self.btn_main_me17 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_main_me17.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_main_me17.setMaximumSize(QtCore.QSize(99999, 99999))
        self.btn_main_me17.setObjectName("btn_main_me17")
        self.verticalLayout.addWidget(self.btn_main_me17)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_me14 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_me14.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_me14.setMaximumSize(QtCore.QSize(99999, 99999))
        self.btn_me14.setObjectName("btn_me14")
        self.verticalLayout_2.addWidget(self.btn_me14)
        self.btn_me18 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_me18.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_me18.setMaximumSize(QtCore.QSize(99999, 99999))
        self.btn_me18.setObjectName("btn_me18")
        self.verticalLayout_2.addWidget(self.btn_me18)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_connect.setText(_translate("MainWindow", "*ME17*"))
        self.btn_me17.setText(_translate("MainWindow", "ME17"))
        self.btn_main_me17.setText(_translate("MainWindow", "*ME17*"))
        self.btn_me14.setText(_translate("MainWindow", "ME14"))
        self.btn_me18.setText(_translate("MainWindow", "ME18"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
